import { db } from "../db";
import { chatEmbeddings } from "@shared/schema";
import { desc, gt, sql } from "drizzle-orm";
import { tryGenerateEmbedding } from "./embedding-service";

/**
 * Chat memory (RAG over chat_embeddings).
 *
 * Embeddings are generated by the unified embedding service (OpenAI
 * text-embedding-3-small at 768 dims — same dimensionality as the previous
 * Gemini text-embedding-004, so existing vector(768) columns stay valid).
 * getEmbedding returns null when no provider key is available for the
 * current user; callers degrade to keyword behaviour.
 */
export class MemoryManager {
    async getEmbedding(text: string): Promise<number[] | null> {
        // Failures are logged with context inside the embedding service.
        return await tryGenerateEmbedding(text, { feature: "chat-memory" });
    }

    async storeMessage(content: string, metadata: Record<string, any>) {
        try {
            const embedding = await this.getEmbedding(content);
            if (!embedding) return;

            await db.insert(chatEmbeddings).values({
                content,
                embedding: embedding,
                metadata
            });
            console.log(`[Memory] Stored message: "${content.substring(0, 30)}..."`);
        } catch (error) {
            console.error("Error storing memory:", error);
        }
    }

    async search(query: string, limit: number = 5, threshold: number = 0.5) {
        try {
            const queryEmbedding = await this.getEmbedding(query);
            if (!queryEmbedding) return [];

            const similarity = sql<number>`1 - (${chatEmbeddings.embedding} <=> ${JSON.stringify(queryEmbedding)}::vector)`;

            const results = await db
                .select({
                    content: chatEmbeddings.content,
                    metadata: chatEmbeddings.metadata,
                    similarity
                })
                .from(chatEmbeddings)
                .where(gt(similarity, threshold))
                .orderBy(desc(similarity))
                .limit(limit);

            return results;
        } catch (error) {
            console.error("Error searching memory:", error);
            return [];
        }
    }
}

export const memoryManager = new MemoryManager();
